[package]
name = "furse"
version = "1.5.1"
edition = "2021"
authors = ["Ilesh Thiada <ileshkt@gmail.com>"]
description = "A simple Rust wrapper for the official CurseForge API"
repository = "https://github.com/theRookieCoder/furse"
license = "MIT"
publish = ["crates-io"]
keywords = ["curseforge", "minecraft", "modding"]
categories = ["api-bindings"]

[dependencies]
reqwest = { version = "~0.11.11", default-features = false, features = [
    "json",
    "rustls-tls",
] }
serde = { version = "~1.0.137", features = ["derive"] }
chrono = { version = "~0.4.19", features = ["serde"] }
url = { version = "~2.2.2", features = ["serde"] }
lazy_static = "~1.4.0"
serde_repr = "~0.1.8"
thiserror = "~1.0.31"
murmur2 = "~0.1.0"
bytes = "~1.1.0"

[dev-dependencies]
tokio = { version = "~1.19.2", features = ["rt-multi-thread", "macros"] }
