[package]
name = "furse"
version = "1.5.9"
edition = "2021"
authors = ["Ilesh Thiada <ileshkt@gmail.com>"]
description = "A simple Rust wrapper for the official CurseForge API"
repository = "https://github.com/gorilla-devs/furse"
license = "MIT"
publish = ["crates-io"]
keywords = ["curseforge", "minecraft", "modding"]
categories = ["api-bindings"]

[dependencies]
reqwest = { version = "0.11.12", default-features = false, features = [
    "json",
    "rustls-tls",
    "blocking",
] }
serde = { version = "1.0.145", features = ["derive"] }
chrono = { version = "0.4.22", features = ["serde"] }
url = { version = "2.2.2", features = ["serde"] }
lazy_static = "1.4.0"
serde_repr = "0.1.9"
thiserror = "1.0.37"
murmur2 = "0.1.0"
serde_urlencoded = "0.7"

[features]
default = ["serde_deny_unknown_fields"]

serde_deny_unknown_fields = []
