[package]
name = "furse"
# The major version specifies which version of the CurseForge API this supports
version = "1.0.0"
edition = "2021"
authors = ["theRookieCoder <ileshkt@gmail.com>"]
description = "A simple library to use the CurseForge API in Rust projects"
repository = "https://github.com/theRookieCoder/furse"
license = "MIT"
publish = ["crates-io"]
keywords = ["curseforge", "minecraft", "modding"]
categories = ["api-bindings", "asynchronous"]
exclude = [
	"example/*"
]

[dependencies]
reqwest = { version = "0", default-features = false, features = ["json", "rustls-tls"] }
chrono = { version = "0", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
bytes = "1"

[dev-dependencies]
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
tokio-test = "0"
